### ISSUE TITLE
能否支持用户自己标记阅读状态

### ISSUE THREAD

**Issue by D3n13d** [AmiaaaZ/chrome-read-later#1]
popup页面里的链接一点开就没，点开但是不代表我读完了（

另外favicon的获取还有有问题，很多网站都获取不到，强迫症犯了😶

**Comment by AmiaaaZ** [comment]
好方略！这就改改改

但是favicon就有点无能为力了……是调用了官方API但是偶尔还是获取不到，这个可能解决不了了（望天）

**Comment by D3n13d** [comment]
🙁好吧，期待下一次的更新

**Comment by AmiaaaZ** [comment]
锐意进行中.gif

**Comment by AmiaaaZ** [comment]
> 🙁好吧，期待下一次的更新

更新已经端上来了！欢迎继续提需求:D
